---
title: "Data Sources"
---

## Datasets
- [Fatal Encounters](https://fatalencounters.org/spreadsheets/)
- [Mapping Police Violence](https://mappingpoliceviolence.us/)
- [California Open Justice (open datasets)](https://openjustice.doj.ca.gov/data)
- [Washington Post Police Shootings Dataset](https://www.washingtonpost.com/graphics/investigations/police-shootings-database/)
- [U of Chicago's Crime lab](https://crimelab.uchicago.edu/)
- [U Miss Library Guide for Crime Statistics](https://libraryguides.missouri.edu/c.php?g=165704&p=1088070)
- [FBI Crime Data Explorer](https://cde.ucr.cjis.gov/LATEST/webapp/#/pages/home)
- [Vera Institute's Incarceration Trends](https://github.com/vera-institute/incarceration-trends)
- [Prison Map - Geography of Incarceration](https://prisonmap.com/)
- [Correctional Procurement Contracts](https://www.prisonpolicy.org/contracts/documents.html)

## Data Collections
These have more tha one dataset, but are not massive clearinghouses
- [Across Walls](https://www.acrosswalls.org/) *This site can be a little difficult to navigate, but they have a lot of specific data not generally available elsewhere, like this [final statements, last meals](https://docs.google.com/spreadsheets/u/1/d/1RF-0BkAVaWwWTlQdkswsfQFmq1x1N4xWL6cHAytuydE/pubhtml) dataset.
- [and other repos by the Vera Institute](https://github.com/vera-institute)


## Data Clearinghouses 
- [ICPSR](https://www.icpsr.umich.edu/sites/icpsr/find-data)
- [Data.gov](https://catalog.data.gov)


## What about _______?
The Prison Policy Initative has a list of [datasets they wish existed](https://www.prisonpolicy.org/blog/2024/12/19/data-wishlist/), but which do not.

## Catherine's Datasets
1. [New York City Surveillance Atlas](https://www.atlasofsurveillance.org/search?location=New+York+City%2C+NY&sort=) Dataset with government information and nonprofit reports on different surveillance technologies in New York City. 
2. [New York City Racial Demographics by Neighborhood](https://www.nyc.gov/assets/dfta/downloads/pdf/reports/Demographics_by_NTA.pdf) A tabulation of the proportion of racial demographics, broken down by neighborhood in each borough in New York. 
3. [Incarceration Rates by Race](https://raw.githubusercontent.com/vera-institute/incarceration-trends/refs/heads/main/incarceration_trends_state.csv) US state-level data on incarceration rates based on racial demographics. 
4. [Map of Police Killings](https://mappingpoliceviolence.us) A database corresponding to a map of police killings across the United States, along with the victim's  information like race and gender. 
5. [Prevalence of Surveillance Cameras in 10 US Cities](https://github.com/Changing-Cities-Research-Lab/surveillance-replication) Data showing the prevalence of surveillance cameras in different neighborhoods across 10 US cities. 